version: 2.1

executors:
  frontend_executor:
    docker:
      - image: circleci/node:carbon
    working_directory: ~/repo

  functions:
    docker:
      - image: circleci/node:carbon
    working_directory: ~/repo/functions

commands:
  deploy_frontend:
    description: "Deploys the frontend to staging or prod"
    parameters:
      env:
        type: enum
        enum: ["staging", "production"]
        default: "staging"
    steps:
      - run: npx firebase use default
      - run: npx firebase deploy --only hosting:<< env >>

  deploy_functions:
    description: "Deploys the cloud functions to staging or prod"
    parameters:
      env:
        type: enum
        enum: ["staging", "production"]
        default: "staging"
    steps:
      - run: npx firebase use default
      - run: npx firebase deploy --only functions:<< env >>

jobs:
  build_frontend:
    executor: frontend_executor
    parameters:
      build_command:
        type: enum
        enum: ["build", "build:prod"]
        default: "build"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Test Suite
          command: npm run test:coverage
      - run:
          name: Build Application
          command: npm run << parameters.build_command >>
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - build
    deploy_frontend:
      parameters:
        env:
          type: enum
          enum: ["staging", "production"]
          default: "staging"
      executor: frontend_executor
      steps:
        - deploy_frontend << parameters.env >>

workflows:
  frontend_staging:
    jobs:
      - build_frontend:
        filters:
          branches:
            only:
              - master
      - deploy_frontend:
          filters:
            branches:
              only:
                - master
          requires:
            - build_frontend
  frontend_prod:
    jobs:
      - build_frontend:
        filters:
          branches:
            only:
              - /release-.*/
        parameters:
          build_command: "build:prod"
      - deploy_frontend:
        filters:
          branches:
            only:
              - /release-.*/
        parameters:
          env: "production"


  functions_staging: