version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Test Suite
          command: npm run test:coverage
      - run:
          name: Build Application
          command: npm run build
