import { ContentModule } from '../../constants';

export const classModules: Array<ContentModule> = [
  { id: '0', name: 'Functions', complexity: 1 },
  { id: '1', name: 'Map', complexity: 2 },
  { id: '2', name: 'Filter', complexity: 1 },
  { id: '3', name: 'Reduce', complexity: 1 },
  { id: '4', name: 'Higher Order Functions', complexity: 2 },
  { id: '5', name: 'React', complexity: 3 },
  { id: '6', name: 'Higher Order Components', complexity: 4 },
  { id: '7', name: 'Observables', complexity: 3 },
  { id: '8', name: 'Redux', complexity: 2 },
  { id: '9', name: 'Redux Observables', complexity: 3 },
  { id: '10', name: 'Functions', complexity: 1 },
  { id: '11', name: 'Map', complexity: 2 },
  { id: '12', name: 'Filter', complexity: 1 },
  { id: '13', name: 'Reduce', complexity: 1 },
  { id: '14', name: 'Higher Order Functions', complexity: 2 },
  { id: '15', name: 'React', complexity: 3 },
  { id: '16', name: 'Higher Order Components', complexity: 4 },
  { id: '17', name: 'Observables', complexity: 3 },
  { id: '18', name: 'Redux', complexity: 2 },
  { id: '19', name: 'Redux Observables', complexity: 3 },
  { id: '20', name: 'Functions', complexity: 1 },
  { id: '21', name: 'Map', complexity: 2 },
  { id: '22', name: 'Filter', complexity: 1 },
  { id: '23', name: 'Reduce', complexity: 1 },
  { id: '24', name: 'Higher Order Functions', complexity: 2 },
  { id: '25', name: 'React', complexity: 3 },
  { id: '26', name: 'Higher Order Components', complexity: 4 },
  { id: '27', name: 'Observables', complexity: 3 },
  { id: '28', name: 'Redux', complexity: 2 },
  { id: '29', name: 'Redux Observables', complexity: 3 },
];
